---
Name: silverware-countries
---

# Configure Country Dropdown Field:

SilverWare\Countries\Forms\CountryDropdownField:
  invalid_countries:
    - cs
    - ct
    - fq
    - fx
    - jt
    - mi
    - nq
    - nt
    - pc
    - pu
    - pz
    - qu
    - su
    - vd
    - wk
    - yd
